[package]
name = "dns_client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bitvec = "1.0.1"
colog = "1.3.0"
log = "0.4.22"
tokio = { version = "1.43.0", features = ["full", "rt", "rt-multi-thread"] }
tokio-macros = "2.5.0"
